/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_BomberGame_API_BomberGameBOTAPI */

#ifndef _Included_com_BomberGame_API_BomberGameBOTAPI
#define _Included_com_BomberGame_API_BomberGameBOTAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_BomberGame_API_BomberGameBOTAPI
 * Method:    echo
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_BomberGame_API_BomberGameBOTAPI_echo
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
